version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stackmind-backend-dev
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      PORT: 4001
      DATABASE_URL: mongodb://mongodb:27017/stackmind_dev?directConnection=true
      MONGO_URI: mongodb://mongodb:27017/stackmind_dev?directConnection=true
      REDIS_URL: redis://redis:6379
    ports:
      - '4001:4001'
    restart: unless-stopped
    networks:
      - stackmind-dev-network

  mongodb:
    image: mongo:7
    container_name: stackmind-mongodb-dev
    command: ['--bind_ip_all']
    ports:
      - '27017:27017'
    tmpfs:
      - /data/db
    volumes:
      - ./scripts/mongo/init-dev.js:/docker-entrypoint-initdb.d/init-dev.js:ro
    restart: unless-stopped
    networks:
      - stackmind-dev-network

  redis:
    image: redis:7-alpine
    container_name: stackmind-redis-dev
    ports:
      - '6379:6379'
    restart: unless-stopped
    command: redis-server --appendonly no
    networks:
      - stackmind-dev-network

networks:
  stackmind-dev-network:
    name: stackmind-dev-network
